In [1]:
import pandas as pd
import numpy as np

In [36]:
data=pd.read_csv('Data Cleaning & Preprocessing_social_media_dataset - social_media_engagement.csv')
data

      Post_ID       User_Name Post_Type  Likes  Shares  Comments Posted_Date
0           1    andreamoreno      Text   8481  4945.0       473  2025/01/30
1           2  marilynbarajas     Image   6099  4065.0      1859  2024/11/10
2           3           hlane     Image   8980   712.0      1920  2025/02/03
3           4       lmitchell      Text   4358  4138.0      1549  2023/09/08
4           5   turnertimothy      Link   8612     NaN       578  2024/06/29
...       ...             ...       ...    ...     ...       ...         ...
1045      113          bsmith      Link   6971  2688.0      1122  2024/01/18
1046      738    rogersdonald      Link     76  2002.0       543  2023/04/03
1047      905    tchristensen      Text   9698  4510.0      1961  2024/01/24
1048      369          hallen     Video     84  2837.0      1149  2024/05/17
1049      172          eric12      Link   7185  1790.0      1958  2024/12/15

[1050 rows x 7 columns]

In [37]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1050 entries, 0 to 1049
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Post_ID      1050 non-null   int64
 1   User_Name    1050 non-null   object
 2   Post_Type    1050 non-null   object
 3   Likes        1050 non-null   int64
 4   Shares       946 non-null    float64
 5   Comments     1050 non-null   int64
 6   Posted_Date  1050 non-null   object
dtypes: float64(1), int64(3), object(3)
memory usage: 57.5+ KB

In [38]:
data.shape

(1050, 7)

In [39]:
data.describe()

           Post_ID        Likes       Shares     Comments
count  1050.000000  1050.000000   946.000000  1050.000000
mean    502.063810  4902.389524  2504.458774   988.952381
std     289.192757  2849.344362  1441.297847   587.705092
min       1.000000     0.000000     2.000000     1.000000
25%     252.250000  2411.250000  1332.250000   463.000000
50%     503.500000  4925.500000  2486.500000   954.000000
75%     751.750000  7430.000000  3806.000000  1496.750000
max    1000.000000  9955.000000  4984.000000  1997.000000

In [40]:
data.isna().sum()

Post_ID          0
User_Name        0
Post_Type        0
Likes            0
Shares         104
Comments         0
Posted_Date      0
dtype: int64

In [41]:
#Clean fake user names
data=data.drop_duplicates()
data=data[~data['User_Name'].str.match(r'^\d+$',na=False)]
data=data[data['User_Name'].str.len()>3]
data

     Post_ID        User_Name Post_Type  Likes  Shares  Comments Posted_Date
0          1     andreamoreno      Text   8481  4945.0       473  2025/01/30
1          2   marilynbarajas     Image   6099  4065.0      1859  2024/11/10
2          3            hlane     Image   8980   712.0      1920  2025/02/03
3          4        lmitchell      Text   4358  4138.0      1549  2023/09/08
4          5    turnertimothy      Link   8612     NaN       578  2024/06/29
..       ...              ...       ...    ...     ...       ...         ...
995      996       grantjenna      Text   4484  3998.0       679  2023/07/25
996      997    barneskristen     Video   9414  2576.0      1534  2024/07/06
997      998  joshuahernandez     Image   1206  1034.0       183  2024/04/08
998      999       kimberly11      Link   3733   178.0       177  2024/12/24
999     1000   danielsmichael      Link   3043     NaN       549  2024/11/19

[1000 rows x 7 columns]

In [47]:
#Date Format correction
data['Posted_Date']=pd.to_datetime(data['Posted_Date'],errors='coerce')
data

     Post_ID        User_Name Post_Type  Likes  Shares  Comments Posted_Date
0          1     andreamoreno      Text   8481  4945.0       473  2025-01-30
1          2   marilynbarajas     Image   6099  4065.0      1859  2024-11-10
2          3            hlane     Image   8980   712.0      1920  2025-02-03
3          4        lmitchell      Text   4358  4138.0      1549  2023-09-08
4          5    turnertimothy      Link   8612     NaN       578  2024-06-29
..       ...              ...       ...    ...     ...       ...         ...
995      996       grantjenna      Text   4484  3998.0       679  2023-07-25
996      997    barneskristen     Video   9414  2576.0      1534  2024-07-06
997      998  joshuahernandez     Image   1206  1034.0       183  2024-04-08
998      999       kimberly11      Link   3733   178.0       177  2024-12-24
999     1000   danielsmichael      Link   3043     NaN       549  2024-11-19

[1000 rows x 7 columns]

In [48]:
data['Posted_Date'] = data['Posted_Date'].dt.strftime('%Y-%m-%d')
data

     Post_ID        User_Name Post_Type  Likes  Shares  Comments Posted_Date
0          1     andreamoreno      Text   8481  4945.0       473  2025-01-30
1          2   marilynbarajas     Image   6099  4065.0      1859  2024-11-10
2          3            hlane     Image   8980   712.0      1920  2025-02-03
3          4        lmitchell      Text   4358  4138.0      1549  2023-09-08
4          5    turnertimothy      Link   8612     NaN       578  2024-06-29
..       ...              ...       ...    ...     ...       ...         ...
995      996       grantjenna      Text   4484  3998.0       679  2023-07-25
996      997    barneskristen     Video   9414  2576.0      1534  2024-07-06
997      998  joshuahernandez     Image   1206  1034.0       183  2024-04-08
998      999       kimberly11      Link   3733   178.0       177  2024-12-24
999     1000   danielsmichael      Link   3043     NaN       549  2024-11-19

[1000 rows x 7 columns]

In [49]:
#Handling Shares column missing data
data['Shares']=data['Shares'].fillna(0)
data

     Post_ID        User_Name Post_Type  Likes  Shares  Comments Posted_Date
0          1     andreamoreno      Text   8481  4945.0       473  2025-01-30
1          2   marilynbarajas     Image   6099  4065.0      1859  2024-11-10
2          3            hlane     Image   8980   712.0      1920  2025-02-03
3          4        lmitchell      Text   4358  4138.0      1549  2023-09-08
4          5    turnertimothy      Link   8612     0.0       578  2024-06-29
..       ...              ...       ...    ...     ...       ...         ...
995      996       grantjenna      Text   4484  3998.0       679  2023-07-25
996      997    barneskristen     Video   9414  2576.0      1534  2024-07-06
997      998  joshuahernandez     Image   1206  1034.0       183  2024-04-08
998      999       kimberly11      Link   3733   178.0       177  2024-12-24
999     1000   danielsmichael      Link   3043     0.0       549  2024-11-19

[1000 rows x 7 columns]

In [50]:
#Validation
data.isnull().sum()

Post_ID        0
User_Name      0
Post_Type      0
Likes          0
Shares         0
Comments       0
Posted_Date    0
dtype: int64

In [51]:
data.describe()

           Post_ID        Likes       Shares     Comments
count  1000.000000  1000.000000  1000.000000  1000.000000
mean    500.500000  4908.421000  2250.086000   991.682000
std     288.819436  2841.345835  1563.700282   588.413046
min       1.000000     0.000000     0.000000     1.000000
25%     250.750000  2419.500000   737.250000   464.750000
50%     500.500000  4925.500000  2192.500000   961.000000
75%     750.250000  7422.000000  3663.500000  1501.250000
max    1000.000000  9955.000000  4984.000000  1997.000000